# Generated by Django 5.1.4 on 2026-02-09 17:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('feedback', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='exams.exam')),
                ('segment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='exams.answersegment')),
            ],
            options={
                'ordering': ['segment__question_number'],
            },
        ),
    ]
