# Generated by Django 5.1.4 on 2026-02-09 17:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('total_questions', models.PositiveIntegerField()),
                ('max_marks_per_question', models.JSONField(default=list, help_text='List of max marks for each question, e.g. [10, 5, 15]')),
                ('status', models.CharField(choices=[('created', 'Created'), ('processing', 'Processing'), ('review', 'Review'), ('grading', 'Grading'), ('completed', 'Completed')], default='created', max_length=20)),
                ('current_grading_question', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnswerSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anonymous_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('roll_number', models.CharField(max_length=50)),
                ('pdf_file', models.FileField(upload_to='uploads/')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('segmented', 'Segmented'), ('needs_review', 'Needs Review'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_sheets', to='exams.exam')),
            ],
            options={
                'ordering': ['roll_number'],
                'unique_together': {('exam', 'roll_number')},
            },
        ),
        migrations.CreateModel(
            name='AnswerSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_number', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='segments/')),
                ('page_number', models.PositiveIntegerField()),
                ('confidence', models.FloatField(default=1.0, help_text='Detection confidence from Sarvam Vision')),
                ('needs_review', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='exams.answersheet')),
            ],
            options={
                'ordering': ['question_number', 'page_number'],
                'unique_together': {('answer_sheet', 'question_number')},
            },
        ),
    ]
