# Generated by Django 5.1.4 on 2026-02-09 17:49

import exams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersegment',
            name='boundary_data',
            field=models.JSONField(blank=True, default=dict, help_text='Crop coordinates: {y_start, y_end, pages, source}'),
        ),
        migrations.AddField(
            model_name='answersheet',
            name='processing_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='answersegment',
            name='image',
            field=models.ImageField(upload_to=exams.models.segment_upload_path),
        ),
    ]
